config/routes.rb
Music::Application.routes.draw do

  resources :bands
  resources :albums
  resources :tracks
  resources :users, :only => [:create,:new]
  resources :sessions
  get 'users/activate' => 'users#activate'

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :album_type, :band_id, :name

  belongs_to :band
  has_many :tracks, dependent: :destroy

  validates :name, presence: true
  validates_uniqueness_of :name, :scope => [:band_id]


end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name

  has_many :albums, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true

end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :album_id, :name, :track_type, :lyrics

  belongs_to :album

  validates :name, presence: true
  validates_uniqueness_of :name, :scope => [:album_id]

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :session_token

  validates :email, :password, presence: true
  validates :email, uniqueness: true


end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
    @bands = Band.all
  end

  def create
    @album = Album.new(params[:album])
    if @album.save
      flash[:notices] ||= []
      flash[:notices] << "You created an album."

      redirect_to @album
    else
      flash.now[:notices] ||= []
      flash.now[:notices] << "Invalid album name"

      @bands = Band.all
      render :new
    end
  end

  def edit
    @bands = Band.all
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    @name = params[:album][:name]
    if @album.update_attributes(params[:album])
      flash[:notices] ||= []
      flash[:notices] << "You updated an album."

      redirect_to album_url(@album.id)
    else
      flash.now[:notices] ||= []
      flash.now[:notices] << "Invalid album name"

      @bands = Band.all
      render :edit
    end
  end

  def destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :logged_in_and_activated

  def logged_in_and_activated
    unless logged_in? && current_user.activation_token.nil?

      redirect_to new_session_url
    end
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
  end

  def show
    @band = Band.find(params[:id])
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(params[:band])
    if @band.save
      flash[:notices] ||= []
      flash[:notices] << "You created a band"

      redirect_to @band
    else
      flash.now[:notices] ||= []
      flash.now[:notices] << "Invalid band name"

      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(params[:band])
      flash.now[:notices] ||= []
      flash.now[:notices] << "You updated a band"

      redirect_to band_url
    else
      flash.now[:notices] ||= []
      flash.now[:notices] << "Invalid band name"

      render :edit
    end
  end

  def destroy
    Band.destroy!(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :logged_in_and_activated

  def create
    user = User.find_by_email_and_password(params[:user][:email],      params[:user][:password])
    if user
      session_token = SecureRandom.urlsafe_base64
      user.session_token = session_token
      user.save
      session[:session_token] = session_token
      redirect_to bands_url
    else
      flash.now[:notices] ||= []
      flash.now[:notices] << "Invalid email/password"

      render :new
    end
  end

  def destroy
    user = User.find_by_session_token(session[:session_token])
    user.session_token = nil
    user.save
    session[:session_token] = nil
    render :new
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def index
    @tracks = Track.all
  end

  def show
    @track = Track.find(params[:id])
  end

  def new
    @track = Track.new
    @albums = Album.all
  end

  def create
    @track = Track.new(params[:track])
    if @track.save
      flash[:notices] ||= []
      flash[:notices] << "You created a track."
      #redirects to show page for particular track
      redirect_to @track
    else
      flash.now[:notices] ||= []
      flash.now[:notices] << "Invalid track name"

      @albums = Album.all
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    @albums = Album.all
  end

  def update
    @track = Track.find(params[:id])
    @name = params[:track][:name]
    if @track.update_attributes(params[:track])
      flash[:notices] ||= []
      flash[:notices] << "You updated a track."

      redirect_to @track
    else
      flash.now[:notices] ||= []
      flash.now[:notices] << "Invalid track name"

      @albums = Album.all
      render :edit
    end
  end

  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :logged_in_and_activated

  def create
    @user = User.new(params[:user])
    if @user.save
      activation_token = SecureRandom.urlsafe_base64
      @user.activation_token = activation_token
      @user.save

      flash[:notices] ||= []
      flash[:notices] << "You created a user."
      msg = UserMailer.welcome_email(@user)
      msg.deliver!

      #login page with flash to go to email and activate
      redirect_to new_session_url
    else
      flash.now[:notices] ||= []
      flash.now[:notices] << "Invalid email/password"

      render :new
    end
  end

  def activate
    user = User.find_by_activation_token(params[:token])
    user.activation_token = nil
    user.save

      #login
    redirect_to new_session_url
  end

end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/band_helper.rb
module BandHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/track_helper.rb
module TrackHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit.html.erb
<h1>Album Editor</h1>
<form action= <%= album_url %> method="post">
  <input type="hidden" name="_method" value="put">
<%= render :partial => "shared/album_form" %>
  <input type="submit" value="Update Album">
</form>

app/views/albums/index.html.erb
<h1>Albums Index</h1>

<ul>
  <% @albums.each do |album| %>
    <li>
      <a href = <%= album_url(album.id) %>><%= "#{album.name}" %></a>
    </li>
  <% end %>
</ul>

<form action= <%= session_url(User.find_by_session_token(session[:session_token])) %> method="post">
  <input type= "hidden" name= "_method" value= "delete">
  <input type="submit" value="Logout">
</form>

app/views/albums/new.html.erb
<h1>Album Creator</h1>
<form action= <%= albums_url %> method="post">
<%= render :partial => "shared/album_form" %>
  <input type="submit" value="Create Album">
</form>

app/views/albums/show.html.erb
<h1><%= "#{@album.name}" %></h1>
<a href = <%= edit_album_url(@album.id) %>>Edit</a>

<% flash[:notices].try(:each) do |msg| %>
  <%= msg %>
<% end %>

<ul>
  <% @album.tracks.each do |track| %>
    <li>
      <a href = <%= track_url(track.id) %>><%= "#{track.name}" %></a>
      <a href = <%= edit_track_url(track.id) %>>Edit</a>
    </li>
    <% end %>
</ul>

<form action= <%= session_url(User.find_by_session_token(session[:session_token])) %> method="post">
  <input type= "hidden" name= "_method" value= "delete">
  <input type="submit" value="Logout">
</form>

app/views/bands/edit.html.erb
<%= render :partial => "shared/band_form" %>

app/views/bands/index.html.erb
<h1>Bands Index</h1>

<ul>
  <% @bands.each do |band| %>
    <li>
      <a href = <%= band_url(band.id) %>><%= "#{band.name}" %></a>
    </li>
  <% end %>
</ul>

<form action= <%= session_url(User.find_by_session_token(session[:session_token])) %> method="post">
  <input type= "hidden" name= "_method" value= "delete">
  <input type="submit" value="Logout">
</form>

app/views/bands/new.html.erb
<h1>Band Creator</h1>
<%= render :partial => "shared/band_form" %>

app/views/bands/show.html.erb
<h1><%= "#{@band.name}" %> </h1>
<a href = <%= edit_band_url(@band.id) %>>Edit</a>

<% flash[:notices].try(:each) do |msg| %>
  <%= msg %>
<% end %>

<ul>
  <% @band.albums.each do |album| %>
    <li>
      <a href = <%= album_url(album.id) %>><%= "#{album.name}" %></a>
    </li>
  <% end %>
</ul>

<form action= <%= session_url(User.find_by_session_token(session[:session_token])) %> method="post">
  <input type= "hidden" name= "_method" value= "delete">
  <input type="submit" value="Logout">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Music</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<p><h2><a href = <%= new_band_url %>>Create a Band</a><p>
<p><h2><a href = <%= new_album_url %>>Create an Album</a><p>
<p><h4><a href = <%= bands_url %>>All Bands</a><p>
<a href = <%= albums_url %>>All Albums</a>

</body>
</html>

app/views/shared/_album_form.html.erb
<% flash[:notices].try(:each) do |msg| %>
  <%= msg %>
<% end %>
<br>

<input type="hidden"
       name="authenticity_token"
       value="<%= form_authenticity_token %>">

  <label for="album_name">Album Name</label>
  <input type="text" name="album[name]" id="album_name" value="<%=@album.name%>">

  <label for="band">Band</label>
  <select name="album[band_id]" id="band">
  <% @bands.each do |band| %>
  <option <%= 'selected' if band.id == @album.band_id %>
    value =<%=band.id%>><%=band.name%></option>
  <% end %>
  </select>

  <label for="type">Album Type</label>
  <select name="album[album_type]" id="type">
    <option <%= 'selected' if @album.album_type == 'studio' %> value =<%="studio"%>>Studio</option>
    <option <%= 'selected' if @album.album_type == 'live' %> value =<%="live"%>>Live</option>
  </select>

  <form action= <%= session_url(User.find_by_session_token(session[:session_token])) %> method="post">
  <input type= "hidden" name= "_method" value= "delete">
  <input type="submit" value="Logout">
</form>

app/views/shared/_band_form.html.erb
<% flash[:notices].try(:each) do |msg| %>
  <%= msg %>
<% end %>


<%= form_for @band do |f|%>
<%= f.label :name, 'Band Name' %>
<%= f.text_field :name %><br>
<%= f.submit %>
<% end %>

<form action= <%= session_url(User.find_by_session_token(session[:session_token])) %> method="post">
  <input type= "hidden" name= "_method" value= "delete">
  <input type="submit" value="Logout">
</form>

app/views/shared/_track_form.html.erb
<% flash[:notices].try(:each) do |msg| %>
  <%= msg %>
<% end %>
<br>
<input type="hidden"
       name="authenticity_token"
       value="<%= form_authenticity_token %>">

  <label for="track_name">Track Name</label>
  <input type="text" name="track[name]" id="track_name" value="<%=@track.name%>">

  <label for="album">Album</label>
  <select name="track[album_id]" id="album">
  <% @albums.each do |album| %>
  <option <%= 'selected' if album.id == @track.album_id %>
    value =<%=album.id%>><%=album.name%></option>
  <% end %>
  </select>

  <label for="type">Track Type</label>
  <select name="track[track_type]" id="type">
    <option <%= 'selected' if @track.track_type == 'regular' %> value =<%="regular"%>>Regular</option>
    <option <%= 'selected' if @track.track_type == 'bonus' %> value =<%="bonus"%>>Bonus</option>
  </select>

  <label for="lyrics">Lyrics</label>
  <textarea name="track[lyrics]" id="lyrics" ><%=@track.lyrics%></textarea>

<form action= <%= session_url(User.find_by_session_token(session[:session_token])) %> method="post">
  <input type= "hidden" name= "_method" value= "delete">
  <input type="submit" value="Logout">
</form>

app/views/tracks/edit.html.erb
<h1>Track Editor</h1>
<form action= <%= track_url %> method="post">
  <input type="hidden" name="_method" value="put">
<%= render :partial => "shared/track_form" %>
  <input type="submit" value="Update Track">
</form>

app/views/tracks/index.html.erb
<h1>Tracks Index</h1>

<ul>
  <% @tracks.each do |track| %>
    <li>
      <a href = <%= track_url(track.id) %>><%= "#{track.name}" %></a>
    </li>
  <% end %>
</ul>

<form action= <%= session_url(User.find_by_session_token(session[:session_token])) %> method="post">
  <input type= "hidden" name= "_method" value= "delete">
  <input type="submit" value="Logout">
</form>

app/views/tracks/new.html.erb
<h1>Track Creator</h1>
<form action= <%= tracks_url %> method="post">
<%= render :partial => "shared/track_form" %>
  <input type="submit" value="Create Track">
</form>

app/views/tracks/show.html.erb
<h1><%= "#{@track.name}" %></h1>

<p>
  <%= "#{@track.lyrics}" %>
</p>

<ul>
  <li>
    <label for="album">Album:</label>
    <a href = "<%= album_url(@track.album.id) %>" id="band"><%= "#{@track.album.name}" %></a>
  </li>
  <li>
    <label for="band">Band:</label>
    <a href= "<%= band_url(@track.album.band.id) %>" id="band"> <%= "#{@track.album.band.name}" %></a>
  </li>
</ul>

app/views/users/new.html.erb
<h1>User Creator</h1>
<% flash[:notices].try(:each) do |msg| %>
  <%= msg %>
<% end %>
<br>
<form action= <%= users_url %> method="post">
  <label for="email">Email</label>
  <input type="text" name = "user[email]" id="email">

  <label for="password">Password</label>
  <input type="password" name = "user[password]" id="password"> <br>

  <input type="submit" value="Create User">
</form> <br>

<a href = <%= new_session_url %>><%= "Login" %></a>